'use client';

import { PageHeader } from '@/components/shared/page-header';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { cicdIntegrationContent } from '@/lib/constants';
import { CodeBlock } from '@/components/shared/code-block';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Terminal, TriangleAlert } from 'lucide-react';

const renderContent = (content: string) => {
    return content.split('```').map((part, index) => {
      if (index % 2 === 1) {
        const [lang, ...code] = part.split('\n');
        return <CodeBlock key={index} code={code.join('\n')} language={lang} className="my-4" />;
      }
      return part.split('\n').map((line, lineIndex) => {
        if (line.startsWith('### ')) {
          return <h3 key={`${index}-${lineIndex}`} className="text-xl font-semibold mt-6 mb-2">{line.substring(4)}</h3>
        }
        if (line.trim() === '') return null;
        return <p key={`${index}-${lineIndex}`} className="mb-2 text-muted-foreground">{line}</p>
      });
    });
  }

export default function CiCdIntegrationPage() {
  return (
    <div>
      <PageHeader
        title="CI/CD Integration (n8n / Scripts)"
        description="Learn how to trigger the AI Test Agent from a script or command line, enabling full automation in your CI/CD pipeline."
      />
      <div className="space-y-8">
        <Alert>
          <Terminal className="h-4 w-4" />
          <AlertTitle>Heads up, developer!</AlertTitle>
          <AlertDescription>
            Integrating with CI/CD requires calling the underlying Next.js Server Action via an HTTP POST request. The examples below show you how to do this.
          </AlertDescription>
        </Alert>

        <Alert variant="destructive">
            <TriangleAlert className="h-4 w-4" />
            <AlertTitle>Important: Action ID Can Change!</AlertTitle>
            <AlertDescription>
                The `Next-Action` header ID is generated by Next.js during the build process. **This ID can change each time you rebuild your application.** If your n8n workflow or script suddenly stops working, the first thing to check is if this ID has changed. You can find the new ID by inspecting the network requests in your browser's developer tools when you run an agent from the web UI.
            </AlertDescription>
        </Alert>

        <Card>
           <CardHeader>
            <CardTitle>Introduction</CardTitle>
            <CardDescription>To run the AI Test Agent automatically in a CI/CD pipeline (like n8n, GitHub Actions, Jenkins, etc.), you can't use the web UI. Instead, you need to trigger the underlying server action using an HTTP POST request.</CardDescription>
          </CardHeader>
          <CardContent className="text-muted-foreground">
            {cicdIntegrationContent.intro}
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            {renderContent(cicdIntegrationContent.curl)}
          </CardContent>
        </Card>

         <Card>
          <CardContent className="pt-6">
            {renderContent(cicdIntegrationContent.node)}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
